### ISSUE TITLE
Happened to find a new paper

### ISSUE THREAD

**Issue by jasperhyp** [basiralab/GNNs-in-Network-Neuroscience#1]
https://proceedings.neurips.cc/paper/2021/file/22785dd2577be2ce28ef79febe80db10-Paper.pdf

**Comment by basiralab** [comment]
Thanks for sharing. This paper did not include papers published in 2021. Can you please double-check the Method section of the GNN review? Thanks.

**Comment by jasperhyp** [comment]
Oh thanks.  I thought you guys would keep updating this repo :)

**Comment by basiralab** [comment]
That is a great suggestion!
